[registries.crates.io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Zthreads=32"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-Zthreads=32"]
